"""Initial travel DB models

Revision ID: 1a45877fad80
Revises: 
Create Date: 2026-01-16 23:16:53.384157

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a45877fad80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_chains_brand'), 'hotel_chains', ['brand'], unique=False)
    op.create_index(op.f('ix_hotel_chains_name'), 'hotel_chains', ['name'], unique=False)
    op.create_table('medical_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('in_assessment', sa.Boolean(), nullable=False),
    sa.Column('otc_code', sa.Integer(), nullable=False),
    sa.Column('otc_list_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('otc_category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('measurement_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('survey_section', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('applies_per_room_type', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_otc_code'), 'questions', ['otc_code'], unique=False)
    op.create_table('travel_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('cvent_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['hotel_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_chain_id'), 'hotels', ['chain_id'], unique=False)
    op.create_index(op.f('ix_hotels_cvent_id'), 'hotels', ['cvent_id'], unique=True)
    op.create_index(op.f('ix_hotels_url'), 'hotels', ['url'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('disability_id', sa.BigInteger(), nullable=False),
    sa.Column('impacted', sa.Integer(), nullable=False),
    sa.Column('impacted_workforce', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Float(), nullable=False),
    sa.Column('labor_stat', sa.Float(), nullable=False),
    sa.Column('statistics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statistics_source', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('labor_source', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('definition_source', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['disability_id'], ['disabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_disability_id'), 'market_data', ['disability_id'], unique=False)
    op.create_table('question_category_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['medical_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_category_map_category_id'), 'question_category_map', ['category_id'], unique=False)
    op.create_index(op.f('ix_question_category_map_question_id'), 'question_category_map', ['question_id'], unique=False)
    op.create_table('question_disability_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('disability_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['disability_id'], ['disabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_disability_map_disability_id'), 'question_disability_map', ['disability_id'], unique=False)
    op.create_index(op.f('ix_question_disability_map_question_id'), 'question_disability_map', ['question_id'], unique=False)
    op.create_table('question_travel_category_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('travel_category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['travel_category_id'], ['travel_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_travel_category_map_question_id'), 'question_travel_category_map', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_travel_category_map_travel_category_id'), 'question_travel_category_map', ['travel_category_id'], unique=False)
    op.create_table('scoring_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_type', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('threshold_min', sa.Integer(), nullable=False),
    sa.Column('threshold_max', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rules_question_id'), 'scoring_rules', ['question_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_hotel_id'), 'contacts', ['hotel_id'], unique=False)
    op.create_table('room_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_type_id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_hotel_id'), 'answers', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_room_type_id'), 'answers', ['room_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_room_type_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_hotel_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_contacts_hotel_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_scoring_rules_question_id'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_question_travel_category_map_travel_category_id'), table_name='question_travel_category_map')
    op.drop_index(op.f('ix_question_travel_category_map_question_id'), table_name='question_travel_category_map')
    op.drop_table('question_travel_category_map')
    op.drop_index(op.f('ix_question_disability_map_question_id'), table_name='question_disability_map')
    op.drop_index(op.f('ix_question_disability_map_disability_id'), table_name='question_disability_map')
    op.drop_table('question_disability_map')
    op.drop_index(op.f('ix_question_category_map_question_id'), table_name='question_category_map')
    op.drop_index(op.f('ix_question_category_map_category_id'), table_name='question_category_map')
    op.drop_table('question_category_map')
    op.drop_index(op.f('ix_market_data_disability_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_hotels_url'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_cvent_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_chain_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_table('travel_categories')
    op.drop_index(op.f('ix_questions_otc_code'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('medical_categories')
    op.drop_index(op.f('ix_hotel_chains_name'), table_name='hotel_chains')
    op.drop_index(op.f('ix_hotel_chains_brand'), table_name='hotel_chains')
    op.drop_table('hotel_chains')
    op.drop_table('disabilities')
    # ### end Alembic commands ###
