"""Added taxonomy keys

Revision ID: 26c554ed53fb
Revises: ad02ad8408ea
Create Date: 2026-01-19 18:04:20.116047

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c554ed53fb'
down_revision: Union[str, Sequence[str], None] = 'ad02ad8408ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disabilities', sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_disabilities_disability_key'), table_name='disabilities')
    op.drop_index(op.f('ix_disabilities_name'), table_name='disabilities')
    op.create_index(op.f('ix_disabilities_key'), 'disabilities', ['key'], unique=True)
    op.create_unique_constraint(None, 'disabilities', ['name'])
    op.drop_column('disabilities', 'description')
    op.drop_column('disabilities', 'disability_key')
    op.add_column('medical_categories', sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_medical_categories_key'), 'medical_categories', ['key'], unique=True)
    op.create_unique_constraint(None, 'medical_categories', ['name'])
    op.add_column('questions', sa.Column('is_range', sa.Boolean(), nullable=False))
    op.drop_column('scoring_rules', 'score')
    op.add_column('travel_categories', sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_travel_categories_key'), 'travel_categories', ['key'], unique=True)
    op.create_unique_constraint(None, 'travel_categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travel_categories', type_='unique')
    op.drop_index(op.f('ix_travel_categories_key'), table_name='travel_categories')
    op.drop_column('travel_categories', 'key')
    op.add_column('scoring_rules', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('questions', 'is_range')
    op.drop_constraint(None, 'medical_categories', type_='unique')
    op.drop_index(op.f('ix_medical_categories_key'), table_name='medical_categories')
    op.drop_column('medical_categories', 'key')
    op.add_column('disabilities', sa.Column('disability_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('disabilities', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'disabilities', type_='unique')
    op.drop_index(op.f('ix_disabilities_key'), table_name='disabilities')
    op.create_index(op.f('ix_disabilities_name'), 'disabilities', ['name'], unique=True)
    op.create_index(op.f('ix_disabilities_disability_key'), 'disabilities', ['disability_key'], unique=True)
    op.drop_column('disabilities', 'key')
    # ### end Alembic commands ###
