"""Added market data disability definition

Revision ID: 27c72e672a9c
Revises: 864e9528f26e
Create Date: 2026-01-17 11:04:27.219444

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c72e672a9c'
down_revision: Union[str, Sequence[str], None] = '864e9528f26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'definition')
    # ### end Alembic commands ###
