"""Added role column to contacts

Revision ID: 33eb3acb5f6b
Revises: cda5d556011a
Create Date: 2026-01-20 12:02:24.642081

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eb3acb5f6b'
down_revision: Union[str, Sequence[str], None] = 'cda5d556011a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False))
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_index(op.f('ix_hotel_chains_name'), table_name='hotel_chains')
    op.create_index(op.f('ix_hotel_chains_name'), 'hotel_chains', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_chains_name'), table_name='hotel_chains')
    op.create_index(op.f('ix_hotel_chains_name'), 'hotel_chains', ['name'], unique=False)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.drop_column('contacts', 'role')
    # ### end Alembic commands ###
