"""Added survey response model

Revision ID: 3b2c94f14183
Revises: f62dc94ee528
Create Date: 2026-01-25 17:35:39.903883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2c94f14183'
down_revision: Union[str, Sequence[str], None] = 'f62dc94ee528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hotel_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_email'), 'survey_responses', ['email'], unique=False)
    op.create_index(op.f('ix_survey_responses_hotel_contact_id'), 'survey_responses', ['hotel_contact_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_response_id'), 'survey_responses', ['response_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_response_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_hotel_contact_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_email'), table_name='survey_responses')
    op.drop_table('survey_responses')
    # ### end Alembic commands ###
