"""Unique constraint to survey response ID

Revision ID: 4e4498bdb6b8
Revises: 3b2c94f14183
Create Date: 2026-01-25 17:59:38.553127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4498bdb6b8'
down_revision: Union[str, Sequence[str], None] = '3b2c94f14183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_response_id'), table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_response_id'), 'survey_responses', ['response_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_response_id'), table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_response_id'), 'survey_responses', ['response_id'], unique=False)
    # ### end Alembic commands ###
