"""Made question survey section nullable

Revision ID: 835cf17d4723
Revises: 33eb3acb5f6b
Create Date: 2026-01-23 19:03:29.916498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835cf17d4723'
down_revision: Union[str, Sequence[str], None] = '33eb3acb5f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'phone',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('hotels', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('questions', 'survey_section',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'survey_section',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('hotels', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('hotels', 'phone',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###
