"""Added disability key, index and constraints

Revision ID: 864e9528f26e
Revises: e9b212410459
Create Date: 2026-01-17 10:41:23.897730

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864e9528f26e'
down_revision: Union[str, Sequence[str], None] = 'e9b212410459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disabilities', sa.Column('disability_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('disabilities_name_key'), 'disabilities', type_='unique')
    op.drop_index(op.f('ix_disabilities_name'), table_name='disabilities')
    op.create_index(op.f('ix_disabilities_name'), 'disabilities', ['name'], unique=True)
    op.create_index(op.f('ix_disabilities_disability_key'), 'disabilities', ['disability_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disabilities_disability_key'), table_name='disabilities')
    op.drop_index(op.f('ix_disabilities_name'), table_name='disabilities')
    op.create_index(op.f('ix_disabilities_name'), 'disabilities', ['name'], unique=False)
    op.create_unique_constraint(op.f('disabilities_name_key'), 'disabilities', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('disabilities', 'disability_key')
    # ### end Alembic commands ###
