"""Changed FK to hotel ID on survey response and removed user email

Revision ID: 932043df3f7b
Revises: 4e4498bdb6b8
Create Date: 2026-01-26 11:42:02.123954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932043df3f7b'
down_revision: Union[str, Sequence[str], None] = '4e4498bdb6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('hotel_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_survey_responses_email'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_hotel_contact_id'), table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_hotel_id'), 'survey_responses', ['hotel_id'], unique=False)
    op.drop_constraint(op.f('survey_responses_hotel_contact_id_fkey'), 'survey_responses', type_='foreignkey')
    op.create_foreign_key(None, 'survey_responses', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('survey_responses', 'hotel_contact_id')
    op.drop_column('survey_responses', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('survey_responses', sa.Column('hotel_contact_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'survey_responses', type_='foreignkey')
    op.create_foreign_key(op.f('survey_responses_hotel_contact_id_fkey'), 'survey_responses', 'contacts', ['hotel_contact_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_survey_responses_hotel_id'), table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_hotel_contact_id'), 'survey_responses', ['hotel_contact_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_email'), 'survey_responses', ['email'], unique=False)
    op.drop_column('survey_responses', 'hotel_id')
    # ### end Alembic commands ###
