"""Updated question and scoring rules models

Revision ID: ad02ad8408ea
Revises: ea4d3a611f4e
Create Date: 2026-01-18 00:22:31.876445

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad02ad8408ea'
down_revision: Union[str, Sequence[str], None] = 'ea4d3a611f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    op.add_column('questions', sa.Column('question_type_notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('questions', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('questions', 'otc_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'otc_list_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'otc_category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'measurement_text',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.add_column('scoring_rules', sa.Column('score', sa.Float(), nullable=False))
    op.alter_column('scoring_rules', 'operator',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=4),
               existing_nullable=False)
    op.alter_column('scoring_rules', 'threshold_min',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('scoring_rules', 'threshold_max',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_scoring_rules_operator'), 'scoring_rules', ['operator'], unique=False)
    op.drop_column('scoring_rules', 'question_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_rules', sa.Column('question_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scoring_rules_operator'), table_name='scoring_rules')
    op.alter_column('scoring_rules', 'threshold_max',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('scoring_rules', 'threshold_min',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('scoring_rules', 'operator',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('scoring_rules', 'score')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.alter_column('questions', 'measurement_text',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'otc_category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'otc_list_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'otc_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('questions', 'question_type_notes')
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
