"""Added place_id to hotel model

Revision ID: cda5d556011a
Revises: 26c554ed53fb
Create Date: 2026-01-20 00:37:48.048941

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda5d556011a'
down_revision: Union[str, Sequence[str], None] = '26c554ed53fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('hotels', 'cvent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_hotels_place_id'), 'hotels', ['place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotels_place_id'), table_name='hotels')
    op.alter_column('hotels', 'cvent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('hotels', 'place_id')
    # ### end Alembic commands ###
