"""Made some fields nullable in answers table

Revision ID: d638cfe8d772
Revises: 932043df3f7b
Create Date: 2026-01-26 19:17:19.938612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd638cfe8d772'
down_revision: Union[str, Sequence[str], None] = '932043df3f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'room_type_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('answers', 'normalized_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'normalized_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('answers', 'room_type_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
