"""Question text index and disability name index

Revision ID: e9b212410459
Revises: 1a45877fad80
Create Date: 2026-01-16 23:36:57.919706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b212410459'
down_revision: Union[str, Sequence[str], None] = '1a45877fad80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_disabilities_name'), 'disabilities', ['name'], unique=False)
    op.create_index(op.f('ix_questions_question_text'), 'questions', ['question_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question_text'), table_name='questions')
    op.drop_index(op.f('ix_disabilities_name'), table_name='disabilities')
    # ### end Alembic commands ###
