"""Added question key and index

Revision ID: ea4d3a611f4e
Revises: 27c72e672a9c
Create Date: 2026-01-17 16:38:51.545639

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4d3a611f4e'
down_revision: Union[str, Sequence[str], None] = '27c72e672a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_index(op.f('ix_questions_question_text'), table_name='questions')
    op.create_index(op.f('ix_questions_question_key'), 'questions', ['question_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question_key'), table_name='questions')
    op.create_index(op.f('ix_questions_question_text'), 'questions', ['question_text'], unique=False)
    op.drop_column('questions', 'question_key')
    # ### end Alembic commands ###
