"""Removed varchar limits in market data

Revision ID: f62dc94ee528
Revises: 295bbb332c5e
Create Date: 2026-01-23 20:54:35.266139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62dc94ee528'
down_revision: Union[str, Sequence[str], None] = '295bbb332c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_data', 'definition',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('market_data', 'impacted',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('market_data', 'impacted_workforce',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('market_data', 'likelihood',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_data', 'labor_stat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_data', 'statistics',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('market_data', 'statistics_source',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('market_data', 'labor_source',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('market_data', 'definition_source',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_data', 'definition_source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('market_data', 'labor_source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('market_data', 'statistics_source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('market_data', 'statistics',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_data', 'labor_stat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_data', 'likelihood',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_data', 'impacted_workforce',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('market_data', 'impacted',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('market_data', 'definition',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
